[General]

# Path relative to Image
Background="Backgrounds/sddm)background.jpg"
# Double between 0 and 1 to darken overlay
DimBackgroundImage="0.0"
#Whether the image should be cropped when scaled
ScaleImageCropped="true"

ScreenWidth="1920"
ScreenHeight="1080"

FullBlur="false"
PartialBlur="true"
BlurRadius="100"

## [Design Customizations]
# Full opacity background color
HaveFormBackground="false"

# Screen Position
FormPosition="center"

# Vertical position of background picture
BackgroundImageHAlignment="center"

# Used for elements when focused/hovered
MainColor="white"
AccentColor="#0000FF"
BackgroundColor="#444"
OverrideLoginButtonTextColor=""
InterfaceShadowSize="6"
InterfaceShadowOpacity="0.6"
RoundCorners="20"
ScreenPadding="0"
Font="Noto Sans"
FontSize=""

## [Interface Behavior]
ForceRightToLeft=false
ForceHideCompletePassword=false
ForceHideVirtualKeyboardButton=false
ForceHideSystemButtons=false

## [Locale Setting]
Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d of MMMM"

## [Translations]
HeaderText="Welcome!"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""